language: python

os:
  - linux
#  - osx

notifications:
  email: false

# sudo: false
sudo: required

matrix:
  fast_finish: true

python:
  - 3.6
#  - 3.5
#  - 3.4

addons:
  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#      - xorg-edgers-ppa
    packages:
#      - gcc-4.8
#      - g++-4.8
#      - Xorg
      - mesa-utils

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi
  - sudo apt-get update
  - sudo apt-get install -y xorg xserver-xorg-video-dummy cpp cpp-6 fontconfig-config fonts-dejavu-core libboost-filesystem1.62.0 libboost-system1.62.0 libcapnp-0.5.3 libdrm-amdgpu1 libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libegl1-mesa libepoxy0 libevdev2 libfontconfig1 libfontenc1 libgbm1 libgl1-mesa-dri libgl1-mesa-glx libglapi-mesa libglu1-mesa libgudev-1.0-0 libice6 libinput-bin libinput10 libisl15 libllvm4.0 libmirclient9 libmircommon7 libmircore1 libmirprotobuf3 libmpc3 libmtdev1 libpciaccess0 libpixman-1-0 libprotobuf-lite10 libsensors4 libsm6 libtxc-dxtn-s2tc libwacom-bin libwacom-common libwacom2 libwayland-client0 libwayland-server0 libx11-xcb1 libxatracker2 libxaw7 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-shape0 libxcb-sync1 libxcb-util1 libxcb-xfixes0 libxcomposite1 libxcursor1 libxdamage1 libxfixes3 libxfont1 libxfont2 libxft2 libxi6 libxinerama1 libxkbcommon0 libxkbfile1 libxmu6 libxpm4 libxrandr2 libxrender1 libxshmfence1 libxss1 libxt6 libxtst6 libxv1 libxvmc1 libxxf86dga1 libxxf86vm1 x11-apps x11-common x11-session-utils x11-utils x11-xkb-utils x11-xserver-utils xbitmaps xfonts-base xfonts-encodings xfonts-scalable xfonts-utils xinit xinput xorg-docs-core xserver-common xserver-xorg xserver-xorg-core xserver-xorg-input-all xserver-xorg-input-libinput xserver-xorg-input-synaptics xserver-xorg-input-wacom xserver-xorg-video-all xserver-xorg-video-amdgpu xserver-xorg-video-ati xserver-xorg-video-fbdev xserver-xorg-video-intel xserver-xorg-video-nouveau xserver-xorg-video-qxl xserver-xorg-video-radeon xserver-xorg-video-vesa xserver-xorg-video-vmware xterm
  - Xorg -noreset +extension GLX +extension RANDR +extension RENDER -logfile ./10.log -config ./xorg.conf :10 >/dev/null 2>&1 &
#  - sudo Xorg +extension GLX +extension RANDR +extension RENDER -logfile xorg.log :200 >xorg.txt 2>&1 &
  - sleep 5
  - cat 10.log
#  - CC=gcc-4.8 CXX=g++-4.8 python setup.py build_ext --inplace
#  - pip install -e .
  - export DISPLAY=:10
  - glxinfo | grep OpenGL
#  - python setup.py install

script: python -m pytest
