language: python

os:
  - linux
#  - osx

# dist: xenial

notifications:
  email: false

sudo: false
# sudo: required

matrix:
  fast_finish: true

compiler:
  - gcc

python:
  - 3.6
#  - 3.5
#  - 3.4

addons:
  apt:
#    sources:
#      - ubuntu-toolchain-r-test
    packages:
#      - gcc-4.8
#      - g++-4.8
      - mesa-utils

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi
  - CC=gcc CXX=g++ python setup.py build_ext -b .
  - glxinfo | grep OpenGL

script: python -m pytest
