language: python

os:
  - linux
#  - osx

notifications:
  email: false

sudo: false

matrix:
  fast_finish: true

python:
  - 3.6
  - 3.5
  - 3.4

# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - gcc-4.8
#       - g++-4.8

install:
  - pip install ModernGL
  - cat /home/travis/virtualenv/python3.6.2rc1/lib/python3.6/site-packages/ModernGL/__init__.py
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi
  - python -c "import ModernGL.mgl"
  - python -c "import ModernGL"

#  - CC=gcc-4.8 CXX=g++-4.8 pip install ModernGL
#  - pip install git+https://github.com/cprogrammer1994/ModernGL -vvv
#  - CC=gcc-4.8 CXX=g++-4.8 pip install git+https://github.com/cprogrammer1994/ModernGL -vvv
#  - glxinfo | grep OpenGL
#  - CC=gcc-4.8 CXX=g++-4.8 python setup.py build_ext --inplace
#  - python setup.py install

script: python -m ModernGL
