language: python

os:
  - linux
#  - osx

notifications:
  email: false

sudo: false

matrix:
  fast_finish: true

python:
  - 3.6
  - 3.5
  - 3.4

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi
  - CC=gcc-4.8 CXX=g++-4.8 python setup.py build_ext --inplace
  - pip install -e .
#  - python setup.py install

script: python -m pytest
