language: python

os:
  - linux
#  - osx

notifications:
  email: false

# sudo: false
sudo: required

matrix:
  fast_finish: true

python:
  - 3.6
#  - 3.5
#  - 3.4

addons:
  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#      - xorg-edgers-ppa
    packages:
#      - gcc-4.8
#      - g++-4.8
#      - Xorg
      - mesa-utils

install:
  - sudo add-apt-repository ppa:oibaf/graphics-drivers
  - sudo apt-get update
  - sudo apt-get upgrade
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi
  - cat /etc/init.d/xvfb
#  - sudo apt-get update
#  - sudo apt-get install -y xorg xserver-xorg-video-dummy xserver-xorg-video-vesa
#  - Xorg -noreset +extension GLX +extension RANDR +extension RENDER -logfile ./10.log -config ./xorg.conf :10 >/dev/null 2>&1 &
#  - sudo Xorg +extension GLX +extension RANDR +extension RENDER -logfile xorg.log :200 >xorg.txt 2>&1 &
#  - sleep 5
#  - cat 10.log
#  - CC=gcc-4.8 CXX=g++-4.8 python setup.py build_ext --inplace
#  - pip install -e .
  - export DISPLAY=:99
  - glxinfo | grep OpenGL
#  - python setup.py install

script: python -m pytest
